#
# Copyright (c) 2021 - Yupiik SAS - https://www.yupiik.com
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Github CI

on: [push, pull_request]

env:
  MAVEN_OPTS: -Dmaven.repo.local=/home/runner/work/yupiik-logging/yupiik-logging/.m2 -Dmaven.artifact.threads=256 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  build:
    name: Main Build
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Cache Maven Repository
        uses: actions/cache@v4
        with:
          path: /home/runner/work/yupiik-logging/yupiik-logging/.m2
          key: m2_repository
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build
        run: mvn install
      - name: Remove Snapshots Before Caching
        run: find /home/runner/work/yupiik-logging/yupiik-logging/.m2 -name '*SNAPSHOT' | xargs rm -Rf
  security_audit:
    name: Security Audit
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Cache Maven Repository
        uses: actions/cache@v4
        with:
          path: /home/runner/work/yupiik-logging/yupiik-logging/.m2
          key: m2_repository
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build
        run: mvn install -DskipTests -Dexec.skip=true ossindex:audit
      - name: Remove Snapshots Before Caching
        run: find /home/runner/work/yupiik-logging/yupiik-logging/.m2 -name '*SNAPSHOT' | xargs rm -Rf
